"""add entry date

Revision ID: d66e8e687ade
Revises: 386a651e34fa
Create Date: 2026-08-19 18:28:46.229339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66e8e687ade'
down_revision: Union[str, Sequence[str], None] = '386a651e34fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column temporarily as nullable
    op.add_column(
        "entries",
        sa.Column(
            "entry_date",
            sa.Date(),
            nullable=True,
        ),
    )

    # Fill existing records using entry_time
    op.execute(
        """
        UPDATE entries
        SET entry_date = entry_time::date
        WHERE entry_date IS NULL
        """
    )

    # Make it NOT NULL after existing rows are populated
    op.alter_column(
        "entries",
        "entry_date",
        existing_type=sa.Date(),
        nullable=False,
    )

    # Create index
    op.create_index(
        op.f("ix_entries_entry_date"),
        "entries",
        ["entry_date"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_entry_date'), table_name='entries')
    op.drop_column('entries', 'entry_date')
    # ### end Alembic commands ###
