"""add deactivated_at to customers

Revision ID: 1a77b905cba5
Revises: d66e8e687ade
Create Date: 2026-08-20 09:29:14.614220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a77b905cba5'
down_revision: Union[str, Sequence[str], None] = 'd66e8e687ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'deactivated_at')
    # ### end Alembic commands ###
